DAY_OBJ = \
	day1/sample1.txt.o \
	day1/input.txt.o \
	day1/solution.o \
	day2/sample1.txt.o \
	day2/input.txt.o \
	day2/solution.o \
	day3/sample1.txt.o \
	day3/sample2.txt.o \
	day3/input.txt.o \
	day3/solution.o \
	day4/sample1.txt.o \
	day4/input.txt.o \
	day4/solution.o \
	day5/sample1.txt.o \
	day5/input.txt.o \
	day5/solution.o \
	day6/sample1.txt.o \
	day6/input.txt.o \
	day6/render.o \
	day6/solution.o \
	day7/sample1.txt.o \
	day7/input.txt.o \
	day7/solution.o \
	day8/sample1.txt.o \
	day8/input.txt.o \
	day8/solution.o \
	day9/sample1.txt.o \
	day9/input.txt.o \
	day9/solution.o \
	day10/sample1.txt.o \
	day10/input.txt.o \
	day10/solution.o \
	day11/sample1.txt.o \
	day11/input.txt.o \
	day11/solution.o
